.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MONITOR" "1" "January 2013" "" ""
.
.SH "NAME"
\fBmonitor\fR \- spy on yourself
.
.SH "SYNOPSIS"
\fBmonitor\fR \fIpath\fR
.
.SH "DESCRIPTION"
While running, \fBmonitor\fR will, at it\'s discretion:
.
.IP "\(bu" 4
Snap a photo with your webcam\.
.
.IP "\(bu" 4
Record the current app\.
.
.IP "\(bu" 4
Record how long you\'ve been idling\.
.
.IP "\(bu" 4
Maybe note down what you\'re listening to\.
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fIpath\fR
Directory output will be written to\.
.
.SH "BUGS"
Boring name is boring\.
.
.SH "AUTHOR"
Sergey Grankin \fIsagran@gmail\.com\fR
.
.SH "COPYRIGHT"
See \fBLICENSE\fR
.
.SH "SEE ALSO"
\fIhttp://news\.ycombinator\.com/item?id=5021783\fR
